# Generated by Django 4.2.7 on 2023-11-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('field_type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('DATE', 'Date'), ('TEXT', 'Text')], default='TEXT', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('fields', models.ManyToManyField(related_name='forms', to='form.field')),
            ],
        ),
    ]
